### ISSUE TITLE
Buffer Allocation Failure on New Peer

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#160]
I ran into this issue earlier this morning with a long running node that is backing HNScan. This node was up for roughly 27 days before receiving this error. I'm about 98% sure this is not a memory failure in terms of the node as on a fresh restart, hsd is only using 13.25% of the machine's memory. 

```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:788:1)
    at Function.alloc (buffer.js:280:10)
    at RollingFilter.fromRate (/code/node_modules/bfilter/lib/rolling.js:70:27)
    at new RollingFilter (/code/node_modules/bfilter/lib/rolling.js:38:12)
    at new Peer (/code/lib/net/peer.js:122:22)
    at Function.fromOutbound (/code/lib/net/peer.js:157:18)
    at Pool.createOutbound (/code/lib/net/pool.js:1112:23)
    at Pool.addOutbound (/code/lib/net/pool.js:3334:23)
    at Pool.fillOutbound (/code/lib/net/pool.js:3360:12)
    at Timeout.pendingRefill.setTimeout [as _onTimeout] (/code/lib/net/pool.js:3374:12)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

**Comment by tynes** [comment]
Interesting find. Which version of Node.js and what operating system?

Looking at the code snippet from where it failed, this is from `bfilter/lib/rolling.js` 

```javascript
  fromRate(items, rate) {
    enforce(Number.isSafeInteger(items) && items > 0, 'items', 'integer');
    enforce(typeof rate === 'number' && isFinite(rate), 'rate', 'number');
    enforce(rate >= 0 && rate <= 1, 'rate', 'range between 0.1 and 1.0.');

    const logRate = Math.log(rate);

    const n = Math.max(1, Math.min(Math.round(logRate / Math.log(0.5)), 50));
    const limit = (items + 1) / 2 | 0;

    const max = limit * 3;

    let size = -1 * n * max / Math.log(1.0 - Math.exp(logRate / n));
    size = Math.ceil(size);

    items = ((size + 63) / 64 | 0) << 1;
    items >>>= 0;
    items = Math.max(1, items);

    const tweak = (Math.random() * 0x100000000) >>> 0;

    const filter = Buffer.alloc(items * 8, 0x00);

    this.n = n;
    this.limit = limit;
    this.size = size;
    this.items = items;
    this.tweak = tweak;
    this.filter = filter;

    return this;
  }
```

Line 70 is where it looks like it actually crashed

```javascript
const filter = Buffer.alloc(items * 8, 0x00);
```

>  I'm about 98% sure this is not a memory failure in terms of the node as on a fresh restart, hsd is only using 13.25% of the machine's memory.

It looks like its an out of memory problem, strange that your machine was reporting such low memory usage. There are known memory issues with Node.js version 9, see https://github.com/bcoin-org/bcoin/issues/754

https://github.com/bcoin-org/bfilter/blob/a3c7e787dd903cff0186ac4385d98df54d369191/lib/rolling.js#L49

**Comment by chjj** [comment]
This is very strange. @kilpatty, can you find the inputs to reproduce this? It should be doable if it's not an OOM. My guess would be that it is an OOM (either because the machine is low on memory, or because `items` somehow overflowed and became super huge).

The typical error message for exceeding the maximum length is different from the message above:

```
> new Uint8Array(-1 >>> 0)
Thrown:
RangeError: Invalid typed array length: 4294967295
    at new Uint8Array (<anonymous>)
```

**Comment by kilpatty** [comment]
Unfortunately I restarted my node immediately after I discovered this as I wanted to bring the block explorer back online. 

I have all my logs still so I'll try to recreate what happened here. One thing that jumps out at me is that I restarted my node this morning and it was running at about 135mb of memory usage - Now it's currently sitting at around 167mb of usage.  So over the course of 1 day it grew ~30mb. If I multiple that growth by the days it was up before crashing (30 x 27) I get roughly 810mb of growth. That combined with the initial memory usage of 135 puts my node right at the point where docker will stop allocating memory to it. 

I'm running 2 plugins (nomenclate and hindexer) so it's possible that 1 of those plugins has a memory leak that caused the memory usage to grow at that rate. 

I'll spin up a new droplet with both a plain hsd daemon running along with one running with both my plugins to see if they are the cause of the memory leak, and report back here my findings.

**Comment by chjj** [comment]
It's possible it was something due to the leveldown rewrite in NAPI. It's also possible urkel is causing it.

@kilpatty, is the memory usage on the native heap or the JS heap? hsd logs this every time a block comes in. If you grep your log files for `memory` you should see it.

**Comment by kilpatty** [comment]
My logs only have a few memory logs as the blocks have been less regular these past few days but here is the ones I can grab: 

```
[D:2019-05-12T13:17:27Z] (chain) Memory: rss=226mb, js-heap=45/54mb native-heap=171mb
[D:2019-05-12T13:20:48Z] (chain) Memory: rss=220mb, js-heap=45/53mb native-heap=166mb
[D:2019-05-12T15:33:53Z] (chain) Memory: rss=217mb, js-heap=45/54mb native-heap=163mb
[D:2019-05-12T15:39:59Z] (chain) Memory: rss=217mb, js-heap=44/54mb native-heap=162mb
[D:2019-05-12T16:46:56Z] (chain) Memory: rss=220mb, js-heap=45/55mb native-heap=164mb
[D:2019-05-12T17:05:00Z] (chain) Memory: rss=219mb, js-heap=45/55mb native-heap=164mb
[D:2019-05-12T17:16:59Z] (chain) Memory: rss=218mb, js-heap=45/54mb native-heap=163mb
[D:2019-05-12T17:29:37Z] (chain) Memory: rss=220mb, js-heap=45/54mb native-heap=165mb
[D:2019-05-13T05:47:58Z] (chain) Memory: rss=212mb, js-heap=46/55mb native-heap=156mb
[D:2019-05-13T05:47:58Z] (chain) Memory: rss=212mb, js-heap=47/55mb native-heap=156mb
[D:2019-05-14T16:30:09Z] (chain) Memory: rss=159mb, js-heap=26/33mb native-heap=125mb
[D:2019-05-14T16:30:09Z] (chain) Memory: rss=159mb, js-heap=26/33mb native-heap=125mb
```

This memory usage growth on the node has been considerably slower without all of these transactions being created in the network, so I'm willing to bet that it has to do with the way I'm indexing them on nomenclate. I haven't had the time to do a thorough check of nomenclate, but I'm hoping I can at some point today.

One more point is that when this was occuring often, HNScan would show hundreds of transactions in the mempool that on a restart would no longer exist. So it seems like transactions were not properly being cleared from the mempool. That being said, I don't imagine that 100-200 transactions in the mempool would cause 800mb of memory usage, so I'm not sure if this is the direct cause of the issue. 

As a side note, I'm not sure if this is relevant or not, but in the grepping of my logs for "memory" I found some strange reorg behavior on May 13th. It appears that my node was being alerted to a competing chains, but not immediately switching the chain tip. Relevant logs for those: 

```
W:2019-05-13T07:41:47Z] (chain) Heads up: Competing chain at height 3871: tip-height=5865 competitor-height=3871 tip-hash=444d2cbff6778efbbdc18e1735bec6e2860c42401df2dad6e3d8acdb429241f5 competitor-hash=4a46f88b7bbd410feed3d2eb2a3856ede2d4acb4ebdb24309fda1e428a1fcde1 tip-chainwork=11503410930737 competitor-chainwork=2745139673077 chainwork-diff=8758271257660
[D:2019-05-13T07:41:47Z] (chain) Memory: rss=136mb, js-heap=46/57mb native-heap=78mb
[I:2019-05-13T07:41:47Z] (chain) Block 4a46f88b7bbd410feed3d2eb2a3856ede2d4acb4ebdb24309fda1e428a1fcde1 (3871) added to chain (size=355 txs=1 time=7.763944).
[W:2019-05-13T07:51:16Z] (chain) Heads up: Competing chain at height 3872: tip-height=5865 competitor-height=3872 tip-hash=444d2cbff6778efbbdc18e1735bec6e2860c42401df2dad6e3d8acdb429241f5 competitor-hash=7b599427e41b609d78c932335b06479388b3befb9d7af9c88dcd0e01f3f43150 tip-chainwork=11503410930737 competitor-chainwork=2745229151562 chainwork-diff=8758181779175
[D:2019-05-13T07:51:16Z] (chain) Memory: rss=139mb, js-heap=45/57mb native-heap=81mb
[I:2019-05-13T07:51:16Z] (chain) Block 7b599427e41b609d78c932335b06479388b3befb9d7af9c88dcd0e01f3f43150 (3872) added to chain (size=355 txs=1 time=8.665594).
```

^ This goes on for 100s of blocks. I'm a bit confused if this is expected behavior or if my node should be switching to a new tip once it accepts a new block e.g. 3872.

**Comment by pinheadmz** [comment]
Closing this due to inactivity and failure to reproduce, also its pretty old and there've been a lot of changes to hsd and nodejs and all the native dependencies since it was opened. @kilpatty feel free of course to reopen if this happens again.
