### ISSUE TITLE
./bin/hsd => SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by kradan** [handshake-org/hsd#35]
```
hsd $ ./bin/hsd
/home/user/engines/hsd/bin/node:72
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

$ ls ~/lib/
libunbound.a  libunbound.la  libunbound.so  libunbound.so.2  libunbound.so.2.5.11

$ npm --version
3.10.10
```

**Comment by Thann** [comment]
Looks to me like an old version of node, try updating or using docker: `docker run handshakeorg/hsd` =]

**Comment by kradan** [comment]
ok, it was at
```
$ node --version
v6.14.1
```
Now with
```
$ node --version
v8.11.3
```
the error is
```
$ ./bin/hsd
Bindings for bcrypto were not built.
Please build them before continuing.
```
README.md does not tell how to link unbound.
```
$ ls ~/lib
libunbound.a  libunbound.la  libunbound.so  libunbound.so.2  libunbound.so.2.5.11
```

**Comment by boymanjor** [comment]
This looks to be resolved. Closing for now.
