### ISSUE TITLE
./bin/hsd: “await” Unexpected reserved word

### ISSUE THREAD

**Issue by lanodan** [handshake-org/hsd#36]
```
/seagate/sources/git/github.com/handshake-org/hsd/lib/node/rpc.js:2287
    for await (const [key, value] of txn) {
        ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/seagate/sources/git/github.com/handshake-org/hsd/lib/node/fullnode.js:17:13)
```
```
$ node --version ; npm --version
v8.1.1
5.0.3
```
```
$ git rev-parse HEAD
d6c7cb56ece9c55863a150eca1234898bc138cf6
```

**Comment by rojii** [comment]
The first thing to came to mind was to just remove the await Promise. It'll run the daemon without error after.

**Comment by tynes** [comment]
@lanodan be sure to use at least Nodejs LTS when running hsd - https://nodejs.org/en/blog/release/v10.13.0/

**Comment by lanodan** [comment]
@tynes 
> be sure to use at least Nodejs LTS when running hsd - https://nodejs.org/en/blog/release/v10.13.0/

This issue was in August 2018, NodeJS 9 and 10 were in current at that time. And it was https://nodejs.org/en/blog/release/v8.11.3/ so wouldn’t have fixed the issue as it’s NodeJS <9.
