### ISSUE TITLE
Error: Invalid bech32 string on address generated with hsw-cli

### ISSUE THREAD

**Issue by dylanjw** [handshake-org/hsd#360]
Im just getting familiar with handshake.  Im hitting the following issue attempting to configure hsd with a coinbase-address.

I created a wallet and receiving address with `hsw-cli`:

```
hs1q7q4eytvaekwumcd29ww4cn0vtlngsx3l5g5z7y
```

in my hsd.conf I put:

```
[...]
coinbase-address: hs1q7q4eytvaekwumcd29ww4cn0vtlngsx3l5g5z7y
[...]
```

Then trying to start hsd I get:

```
/home/dwilson/code/hsd/lib/primitives/address.js:228
    const [hrp, version, hash] = bech32.decode(data);
                                        ^

Error: Invalid bech32 string.
    at Address.fromString (/home/dwilson/code/hsd/lib/primitives/address.js:228:41)
    at Address.fromOptions (/home/dwilson/code/hsd/lib/primitives/address.js:56:19)
    at new Address (/home/dwilson/code/hsd/lib/primitives/address.js:45:12)
    at MinerOptions.fromOptions (/home/dwilson/code/hsd/lib/mining/miner.js:529:31)
    at new MinerOptions (/home/dwilson/code/hsd/lib/mining/miner.js:486:10)
    at new Miner (/home/dwilson/code/hsd/lib/mining/miner.js:43:20)
    at new FullNode (/home/dwilson/code/hsd/lib/node/fullnode.js:114:18)
    at Object.<anonymous> (/home/dwilson/code/hsd/bin/node:42:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
```

What am I doing wrong?

**Comment by pinheadmz** [comment]
Are you sure you have the right address?

```
$ hsd-rpc validateaddress hs1q7q4eytvaekwumcd29ww4cn0vtlngsx3l5g5z7y
{
  "isvalid": false
}
```

Could it be you're not on mainnet? (There would be a different prefix)

**Comment by dylanjw** [comment]
Sorry, I have my lines crossed.  I think I wasnt getting the config saved with the above address, but instead had the address from the example hsd.config.

Thanks!
