### ISSUE TITLE
Bindings for bcrypto were not built.

### ISSUE THREAD

**Issue by popey** [handshake-org/hsd#41]
Cloned the repo and tried to build on my Ubuntu 16.04 system.

```
alan@robby:~/src/hsd⟫ npm install --production
audited 930 packages in 5.098s
found 0 vulnerabilities

alan@robby:~/src/hsd⟫ bin/hsd 
Bindings for bcrypto were not built.
Please build them before continuing.
1 alan@robby:~/src/hsd⟫ node --version
v10.8.0
```

**Comment by chjj** [comment]
Could you copy & paste your build log here? If bcrypto wasn't built, there was probably some build errors in there.

**Comment by dylanbathurst** [comment]
same on arch
```
[dylan@archlinux hsd]$ rm package-lock.json
[dylan@archlinux hsd]$ npm install --production

> bcrypto@1.1.0 install /home/dylan/hsd/node_modules/bcrypto
> node-gyp rebuild || echo 'Build failed.'

make: Entering directory '/home/dylan/hsd/node_modules/bcrypto/build'
  CC(target) Release/obj.target/bcrypto/src/aead/aead.o
make: cc: Command not found
make: *** [bcrypto.target.mk:166: Release/obj.target/bcrypto/src/aead/aead.o] Error 127
make: Leaving directory '/home/dylan/hsd/node_modules/bcrypto/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.14.66-1-lts
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dylan/hsd/node_modules/bcrypto
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed.

> bsip@0.1.1 install /home/dylan/hsd/node_modules/bsip
> node-gyp rebuild || echo 'Build failed.'

make: Entering directory '/home/dylan/hsd/node_modules/bsip/build'
  CXX(target) Release/obj.target/bsip/src/siphash.o
  CXX(target) Release/obj.target/bsip/src/bsip.o
  SOLINK_MODULE(target) Release/obj.target/bsip.node
  COPY Release/bsip.node
make: Leaving directory '/home/dylan/hsd/node_modules/bsip/build'

> mrmr@0.1.1 install /home/dylan/hsd/node_modules/mrmr
> node-gyp rebuild || echo 'Build failed.'

make: Entering directory '/home/dylan/hsd/node_modules/mrmr/build'
  CXX(target) Release/obj.target/mrmr/src/murmur3.o
  CXX(target) Release/obj.target/mrmr/src/mrmr.o
  SOLINK_MODULE(target) Release/obj.target/mrmr.node
  COPY Release/mrmr.node
make: Leaving directory '/home/dylan/hsd/node_modules/mrmr/build'

> unbound@0.1.0 install /home/dylan/hsd/node_modules/unbound
> node-gyp rebuild

make: Entering directory '/home/dylan/hsd/node_modules/unbound/build'
  CXX(target) Release/obj.target/unbound/src/node_unbound.o
  CXX(target) Release/obj.target/unbound/src/node_unbound_async.o
  SOLINK_MODULE(target) Release/obj.target/unbound.node
  COPY Release/unbound.node
make: Leaving directory '/home/dylan/hsd/node_modules/unbound/build'

> bdb@1.1.0 install /home/dylan/hsd/node_modules/bdb
> node-gyp rebuild

make: Entering directory '/home/dylan/hsd/node_modules/bdb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
../deps/leveldb/leveldb-1.20/util/hash.cc: In function 'uint32_t leveldb::Hash(const char*, size_t, uint32_t)':
../deps/leveldb/leveldb-1.20/util/hash.cc:37:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       h += static_cast<unsigned char>(data[2]) << 16;
       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:39:5: note: here
     case 2:
     ^~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:40:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
       h += static_cast<unsigned char>(data[1]) << 8;
       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/leveldb/leveldb-1.20/util/hash.cc:42:5: note: here
     case 1:
     ^~~~
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  AR(target) Release/obj.target/deps/leveldb/leveldb.a
  COPY Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
  CXX(target) Release/obj.target/leveldown/src/batch_async.o
  CXX(target) Release/obj.target/leveldown/src/database.o
  CXX(target) Release/obj.target/leveldown/src/database_async.o
  CXX(target) Release/obj.target/leveldown/src/iterator.o
  CXX(target) Release/obj.target/leveldown/src/iterator_async.o
  CXX(target) Release/obj.target/leveldown/src/leveldown.o
  CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
  SOLINK_MODULE(target) Release/obj.target/leveldown.node
  COPY Release/leveldown.node
make: Leaving directory '/home/dylan/hsd/node_modules/bdb/build'

> bstring@0.2.0 install /home/dylan/hsd/node_modules/bstring
> node-gyp rebuild || echo 'Build failed.'

make: Entering directory '/home/dylan/hsd/node_modules/bstring/build'
  CXX(target) Release/obj.target/bstring/src/base58.o
  CXX(target) Release/obj.target/bstring/src/bech32.o
  CXX(target) Release/obj.target/bstring/src/cashaddr.o
  CXX(target) Release/obj.target/bstring/src/bstring.o
  SOLINK_MODULE(target) Release/obj.target/bstring.node
  COPY Release/bstring.node
make: Leaving directory '/home/dylan/hsd/node_modules/bstring/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 37 packages from 9 contributors and audited 381 packages in 34.913s
found 0 vulnerabilities

[dylan@archlinux hsd]$ ./bin/hsd
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Bindings for bcrypto were not built.
Please build them before continuing.
```

**Comment by sunhongyue4500** [comment]
the same problem. 
Bindings for bcrypto were not built.
Please build them before continuing.
node v8.11.1

**Comment by briansoule** [comment]
+1

**Comment by briansoule** [comment]
Seemed to work when I changed from Node 8 to Node 9

**Comment by tynes** [comment]
@popey A potential fix was merged into `bcrypto@v3.0.3`
See: https://github.com/bcoin-org/bcrypto/issues/10

Can you try again and if you are having the same problem, can you please respond with which version of node you are using? Be sure to try with at least Node 10 LTS

**Comment by no-replies** [comment]
Same issue Node 10

**Comment by tynes** [comment]
@no-replies Can you please share you build logs? It would also be helpful to know your operating system and architecture

**Comment by hannibalhuang** [comment]
I can install bcrypt but still got the same error. Running on macos darwin, nodejs v11

zhipengs-mbp:hsd zhipeng$ npm install bcrypt

> bcrypt@3.0.5 install /Users/zhipeng/Workspace/hsd/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[bcrypt] Success: "/Users/zhipeng/Workspace/hsd/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
+ bcrypt@3.0.5
added 68 packages from 49 contributors and audited 221 packages in 10.657s
found 0 vulnerabilities

zhipengs-mbp:hsd zhipeng$ ./bin/hsd
Bindings for bcrypto were not built.
Please build them before continuing.

**Comment by tynes** [comment]
@hannibalhuang 

Try this command:
```
$ npm rebuild bcrypto
```

It should rebuild `bcrypto`. Note that the dependency is `bcrypto` and not `bcrypt`.
You can see the git repo here: https://github.com/bcoin-org/bcrypto

**Comment by hannibalhuang** [comment]
@tynes it then throws the following err re leveldown, i've tried install it again but no success

zhipengs-mbp:hsd zhipeng$ ./bin/hsd 
/Users/zhipeng/Workspace/hsd/node_modules/loady/lib/loady.js:121
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/build/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/build/Debug/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/build/Release/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/out/Debug/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/Debug/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/out/Release/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/Release/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/build/default/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/compiled/11.13.0/darwin/x64/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/addon-build/release/install-root/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/addon-build/debug/install-root/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/addon-build/default/install-root/leveldown.node
 - /Users/zhipeng/Workspace/hsd/node_modules/bdb/lib/binding/node-v67-darwin-x64/leveldown.node
    at bindings (/Users/zhipeng/Workspace/hsd/node_modules/loady/lib/loady.js:116:15)
    at Object.<anonymous> (/Users/zhipeng/Workspace/hsd/node_modules/bdb/lib/level.js:9:33)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/zhipeng/Workspace/hsd/node_modules/bdb/lib/bdb.js:13:15)

**Comment by tynes** [comment]
@hannibalhuang 

Can you please share your OS, architecture, `node` version and `npm` version?
Be sure that you are using at least Node.js 10.x.x

**Comment by hannibalhuang** [comment]
@tynes I'm running on MacOS Mojave, node v11.13.0 and npm v6.70. I tried to build from a fresh env so everything should be up to date from brew

**Comment by tynes** [comment]
@hannibalhuang 

Can you share `gcc --version`?

Try deleting your `node_modules` and installing via `npm` again.
If any dependency fails to build, you can try `npm rebuild <dependecy>`

For example:

```bash
$ npm rebuild bcyrpto

$ npm rebuild bdb
```

**Comment by hannibalhuang** [comment]
fixed by reinstall bdb and rebuild loady :) Thanks for the handholding

**Comment by boymanjor** [comment]
I'm closing this for now, but anyone should feel free to reopen if this issue comes back up.
