### ISSUE TITLE
Unable to run ./bin/hsd

### ISSUE THREAD

**Issue by yokosogithub** [handshake-org/hsd#452]
My node version is 12.16.3
Ubuntu system
Error message:
/mnt/c/Users/Administrator/Desktop/hsd/node_modules/_loady@0.0.1@loady/lib/loady.js:121
Error: Could not locate the bindings file. Tried:
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/build/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/build/Debug/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/build/Release/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/out/Debug/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/Debug/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/out/Release/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/Release/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/build/default/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/compiled/10.15.0/linux/x64/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/addon-build/release/install-root/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/addon-build/debug/install-root/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/addon-build/default/install-root/leveldown.node
 - /mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/lib/binding/node-v64-linux-x64/leveldown.node
    at bindings (/mnt/c/Users/Administrator/Desktop/hsd/node_modules/_loady@0.0.1@loady/lib/loady.js:116:15)
    at Object.<anonymous> (/mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/lib/level.js:9:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/c/Users/Administrator/Desktop/hsd/node_modules/_bdb@1.2.1@bdb/lib/bdb.js:13:15)

**Comment by tynes** [comment]
Where you sure to run `npm install` first?

**Comment by cjheath** [comment]
I have this problem too. After the first `npm install --production` and `./bin/hsd --log-level info` failed, I ran `npm install leveldown` which installed a number of packages.

A subsequent `./bin/hsd --log-level info` also failed, so I tried to `npm uninstall hsd` followed by installing again.

Still the same failure. Please fix your dependencies.

**Comment by cjheath** [comment]
Update: blowing away node_modules and package-lock.json in both directories fixed it.
