### ISSUE TITLE
Can't Install Goosig : error: ‘bcrypto_init’ undeclared here (not in a function)

### ISSUE THREAD

**Issue by alifianadexe** [handshake-org/hsd#714]
Hey mate, im trying to install hsd and hsd-airdrop but why this get error on goosig. Here the full log : 

```
In file included from ../src/goosig.c:12:0:
../src/goosig.c:234:35: error: ‘bcrypto_init’ undeclared here (not in a function)
 NAPI_MODULE(NODE_GYP_MODULE_NAME, bcrypto_init)                  \
                                   ^
/usr/include/nodejs/src/node_api.h:92:7: note: in definition of macro ‘NAPI_MODULE_X’
       regfunc,                                                        \
       ^~~~~~~
../src/goosig.c:234:1: note: in expansion of macro ‘NAPI_MODULE’
 NAPI_MODULE(NODE_GYP_MODULE_NAME, bcrypto_init)                  \
 ^~~~~~~~~~~
../src/goosig.c:238:1: note: in expansion of macro ‘NAPI_MODULE_INIT’
 NAPI_MODULE_INIT() {
 ^~~~~~~~~~~~~~~~
../src/goosig.c:238:1: warning: missing initializer for field ‘reserved’ of ‘napi_module {aka struct <anonymous>}’ [-Wmissing-field-initializers]
In file included from ../src/goosig.c:12:0:
/usr/include/nodejs/src/node_api.h:59:9: note: ‘reserved’ declared here
   void* reserved[4];
         ^~~~~~~~
../src/goosig.c:235:19: warning: ‘goosig_init’ defined but not used [-Wunused-function]
 static napi_value goosig_init(napi_env env, napi_value exports)
                   ^
../src/goosig.c:238:1: note: in expansion of macro ‘NAPI_MODULE_INIT’
 NAPI_MODULE_INIT() {
 ^~~~~~~~~~~~~~~~
goosig.target.mk:98: recipe for target 'Release/obj.target/goosig/src/goosig.o' failed
make: *** [Release/obj.target/goosig/src/goosig.o] Error 1
make: Leaving directory '/home/adexe/airdrop/hs-airdrop/node_modules/goosig/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/adexe/airdrop/hs-airdrop/node_modules/goosig
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! Linux 4.4.0-19041-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "goosig"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! goosig@0.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the goosig@0.10.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the goosig package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs goosig
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls goosig
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adexe/airdrop/hs-airdrop/node_modules/npm-debug.log
```

Any help?

**Comment by pinheadmz** [comment]
> gyp ERR! node -v v8.10.0

There's your problem.

https://github.com/handshake-org/hsd/blob/master/docs/install.md#install-hsd

> hsd requires Node.js v12 or higher.
