### ISSUE TITLE
Error: Cannot find module 'goosig'

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#79]
Running from master, also tried a "working" commit 7f6e6ba277f43011fa873338fa693e85d4e3a907 hard-coded in bpanel.

```
$ hsd
module.js:557
    throw err;
    ^

Error: Cannot find module 'goosig'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/matthewzipkin/Desktop/work/hsd/lib/primitives/airdropkey.js:13:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

I even manually installed goosig:
`npm install goosig`

```
$ npm list goosig
hsd@0.0.0 /Users/matthewzipkin/Desktop/work/install/dist/app/libs/hsd
└── goosig@0.0.2 
```

...but strangely this does not fix the error

**Comment by pinheadmz** [comment]
Seems to be a user error on my part, I was running the wrong version
